# Generated by Django 4.2 on 2023-04-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="countrymodel",
            name="country_name",
            field=models.CharField(default="", max_length=30),
        ),
    ]
