# Generated by Django 4.2 on 2023-04-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0002_countrymodel_country_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangemodel", name="rate", field=models.FloatField(null=True),
        ),
    ]
