# Generated by Django 4.2 on 2023-04-17 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0003_alter_exchangemodel_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countrymodel",
            name="country_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="superadmin.exchangemodel",
            ),
        ),
    ]
