# Generated by Django 4.2 on 2023-04-17 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0004_alter_countrymodel_country_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangemodel",
            name="country_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="superadmin.countrymodel",
            ),
        ),
        migrations.AlterField(
            model_name="countrymodel",
            name="country_id",
            field=models.CharField(max_length=3),
        ),
    ]
