# Generated by Django 4.2 on 2023-04-17 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0005_exchangemodel_country_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangemodel",
            name="country_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="superadmin.countrymodel",
            ),
        ),
    ]
