# Generated by Django 4.2 on 2023-04-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0006_alter_exchangemodel_country_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="exchangemodel", name="country_name",),
    ]
