# Generated by Django 4.2 on 2023-04-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0007_remove_exchangemodel_country_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangemodel",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
